version: '3'
services:
#  nginx:
#      image: nginx:latest
#      container_name: express_mongo_proxy_1
#      volumes:
#        - ./config/nginx.conf:/etc/nginx/nginx.conf
##        - ./nginx/log:/var/log/nginx/
##        - ./nginx/cache/:/etc/nginx/cache
#      ports:
#        - 80:80
#        - 443:443
##      networks:
##        - express-mongo-network
#      depends_on:
#        - api
#      links:
#        - api

  db:
    image: mongo:latest
    restart: always
    container_name: express_mongo_db_1
    volumes:
      - ./db_mongo:/data/db
    ports:
      - 27017:27017

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    restart: always
    container_name: express_mongo_api_1
    environment:
      - NODE_ENV=dev
      - DB_HOST=db
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 9000:9000
    links:
      - db
    depends_on:
      - db
